apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmops-chat.fullname" . }}
  labels:
    {{- include "llmops-chat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llmops-chat.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "llmops-chat.fullname" . }}
  labels:
    {{- include "llmops-chat.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "llmops-chat.fullname" . }}
                port:
                  name: http
{{- end }}
