apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llmops
resources:
  - namespace.yaml
  - pvc-model.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: sufyanliaqat/llmops-chat
    newName: sufyanliaqat/llmops-chat
    newTag: "0.1.0"
