apiVersion: v1
kind: Service
metadata:
  name: llmops-chat
  namespace: llmops
  labels:
    app.kubernetes.io/name: llmops-chat
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: llmops-chat
  ports:
    - name: http
      port: 80
      targetPort: http
